import json
m = json.load(open("viewer/manifest.json", encoding="utf-8"))
SITE = "https://tomosud.github.io/Odyssey/"
def roman(e): return e["roman"]
lines = []
lines.append("# オデュッセイア 縦書きビュワー")
lines.append("")
lines.append("ホメロス『オデュッセイア』(Samuel Butler の散文英訳 / Project Gutenberg #1727 を底本とした")
lines.append("現代日本語訳)を、**読みやすい縦書き(tategaki)** で読むための Web ビュワーです。")
lines.append("`Odyssey/02_和訳`(全24歌の和訳)と `Odyssey/04_事典`(人物・地名の索引)の Markdown を")
lines.append("そのままソースとして表示します。")
lines.append("")
lines.append(f"## ▶ ビュワーを開く")
lines.append("")
lines.append(f"**<{SITE}>**")
lines.append("")
lines.append("- 和訳は縦書き(右→左)で表示。ホイール/矢印キー(←→)・下部のリンクで歌を移動できます。")
lines.append("- 事典は横書きの一覧で、名前・原文表記・説明をまたいで**絞り込み検索**できます。")
lines.append("- ライト/ダークテーマ、PC・スマートフォンに対応。")
lines.append("")
lines.append("## エントリ一覧")
lines.append("")
lines.append("### 和訳(全24歌)")
lines.append("")
lines.append("| 歌 | 見出し | リンク |")
lines.append("|---|---|---|")
for e in m["wayaku"]:
    url = f"{SITE}#/wayaku/{e['book']}"
    lines.append(f"| 第{e['book']}歌 (BOOK {roman(e)}) | {e['heading']} | [開く]({url}) |")
lines.append("")
lines.append("### 事典(索引)")
lines.append("")
lines.append("| 索引 | リンク |")
lines.append("|---|---|")
for j in m["jiten"]:
    url = f"{SITE}#/jiten/{j['slug']}"
    lines.append(f"| {j['label']} | [開く]({url}) |")
lines.append("")
lines.append("## 仕組み")
lines.append("")
lines.append("- `index.html` … ビュワーのエントリ(サイトのトップ)")
lines.append("- `viewer/viewer.css`, `viewer/viewer.js` … 表示ロジック(外部ライブラリ非依存)")
lines.append("- `viewer/manifest.json` … 目次データ(各歌のタイトルと Markdown へのパス)")
lines.append("- `.nojekyll` … GitHub Pages に Markdown を加工せずそのまま配信させるためのファイル")
lines.append("")
lines.append("`viewer/manifest.json` は各和訳ファイルの frontmatter(`heading_ja` 等)から生成しています。")
lines.append("歌を追加・改題したときは manifest を更新してください。")
lines.append("")
lines.append("> 翻訳・整備プロジェクトそのものの記述ルールは [`Odyssey/README.md`](Odyssey/README.md) を参照。")
lines.append("")
open("README.md","w",encoding="utf-8").write("\n".join(lines))
print("wrote README.md")
print("\n".join(lines[:40]))
